name: goshawk
channels:
  - conda-forge
dependencies:
  - python=3.10
  - spectral=0.23.1
  - numpy=1.26.4
  - ipykernel
  - google-cloud-sdk
  - earthengine-api
  - pandas
  - dask
  - matplotlib
  - scipy=1.11.3
  - py3dep=0.15.2
  - mpi4py=3.1.4
  - pip
  - pip:
    - ray[default]==2.7.0 
    - hy-tools==1.5.0
    - elevation==1.1.3 
    - dem_stitcher==2.5.0
    - pysolar==0.11
    - topocalc==0.5.0