name: goshawk
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - spectral=0.23.1
  - numpy
  - ipykernel
  - google-cloud-sdk
  - earthengine-api
  - pandas
  - pyspark=3.4.1
  - matplotlib
  - scipy=1.11.2
  - py3dep=0.15.0
  - mpi4py=3.1.4
  - pip
  - pip:
    - ray[default]=2.6.3 
    - hy-tools=1.5.0
    - elevation=1.1.3 
    - dem_stitcher=2.5.0
    - pysolar=0.11
    - topocalc=0.5.0

